routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Str;

Route::prefix('back-office')->namespace('BackOffice')->group(function () {
    Auth::routes();

    Route::get('', function () {
        return view('layouts.backoffice.master');
    })->middleware('auth')->name('bo.home');

    Route::prefix('standing-orders')->namespace('SO')->middleware('auth')->name('so.')->group(function () {
        Route::get('pending', 'SoController@pending')->name('pending');
        Route::get('pending/{payment_ref}/view', 'SoController@view')->name('pending.view');
        Route::get('activated', 'SoController@activated')->name('activated');
        Route::get('invalid', 'SoController@invalid')->name('invalid');
    });

    Route::prefix('roles')->namespace('Roles')->middleware('auth')->group(function () {
        Route::get('/', 'RoleController@index')->name('roles.index');
        Route::post('/', 'RoleController@store')->name('roles.store');
        Route::delete('/{role}', 'RoleController@destroy')->name('roles.destroy');

        Route::get('assign', 'AssignRolesToPermsController@index')->name('roles.assign');
        Route::post('assign', 'AssignRolesToPermsController@store')->name('assign.create');
    });
    Route::prefix('abilities')->namespace('Roles')->middleware('auth')->group(function () {
        Route::get('/', 'AbilityController@index')->name('abilities.index');
        Route::post('/', 'AbilityController@store')->name('abilities.store');
        Route::delete('/{ability}', 'AbilityController@destroy')->name('abilities.destroy');
    });
    Route::prefix('users')->middleware('auth')->group(function () {
        Route::get('/', 'UserController@index')->name('users.index');
        Route::get('show/{user}', 'UserController@show')->name('users.show');
    });

    Route::prefix('loan-app')->middleware('auth')->namespace('LoanApp')->name('bo.loan.')->group(function () {
        Route::get('loan-requests', 'LoanRequestController@index')->name('requests');
        Route::get('{id}/loan-request', 'LoanRequestController@show')->name('show');

        Route::get('remita-salary-history', 'LoanRequestController@remitaSalaryHistory');
    });


    Route::get('test', function (\App\Library\SalaryHistoryWrapper $wrapper, \App\Library\DoScoring $doScoring) {

        dd(
            \App\Models\Transaction::first()->standingOrder->first(),
            \App\Models\Transaction::first()->Customer->first(),
            \App\Models\Transaction::first()->authorization()->first()
        );


        //echo toNaira(roundNearestHundredUp(pv(7/100, 6, 21000)));
    });


});
Route::get('start-loan-request', function () {
    return view('front.loan-request.start');
})->name('start.request');
Route::prefix('auth')->namespace('Front\Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('auth.login');
    Route::post('login', 'LoginController@login')->name('auth.post.login');
    Route::post('logout', 'LoginController@logout');
    Route::get('logout', 'LoginController@logout')->name('auth.logout');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail');
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm');
    Route::post('register', 'RegisterController@register');
    Route::get('register', 'RegisterController@showRegistrationForm');

    Route::get('home', function () {
        return 'Auth Home';
    })->middleware('ap.auth:ap')->name('auth.home');
});

Route::prefix('user')->namespace('Front')->middleware('ap.auth:ap')->name('user.')->group(function () {
    Route::get('home', 'AppController@home')->name('home');
    Route::get('loan-requests', 'AppController@loanRequests')->name('requests');
    Route::get('/loan-request/{requestId}/view', 'AppController@showLoanRequest')->name('request');
});


Route::get('/', function () {
    return view('welcome');
});

Route::prefix('standing-order')->namespace('StandingOrder')->group(function () {

    Route::get('', 'StandingOrderController@create')->name('so.create');
    Route::get('/', 'StandingOrderController@create')->name('so.create');
    Route::get('create', 'StandingOrderController@create')->name('so.create');
    Route::get('verify-initial-charge', 'StandingOrderController@verify')->name('so.verify.reference');

    Route::get('test', 'StandingOrderController@test');
});

Route::get('backoffice/standing-order', function () {

    $p = new ShegunBabs\PayStack\PayStack(env('PAYSTACK_SECRET_KEY'));
    $response = $p->transaction->initialize(['email' => 'shegun.babs@gmail.com', 'amount' => 1000 * 100, 'callback_url' => 'http://loanapp.local/standing-order/verify-initial-charge']);
    $url = $response['response']->data->authorization_url;
    dd($url);

    //ShegunBabs\PayStack\call_url($url);

    //return view('bo.standing-order');
});

Route::get('standing-order/verify-initial-charges', function (Request $request) {

    $trxref = $request->query('trxref');
    $ref = $request->query('reference');

    if (empty($ref)) {
        return view('bo.so.noref');
    }


    $p = new \ShegunBabs\PayStack\PayStack(env('PAYSTACK_SECRET_KEY'));
    $res = $p->transaction->verify($ref);
    Log::info($res['response']);
    dd($res['response']);
});

Route::get('privacy-policy', 'FrontOffice\WebController@privacy');

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('test')->group(function () {

    Route::get('sms', function(){
        $res = app('Infobip')->sms->single([

        ]);
    });

    Route::get('mail', function () {
        $loanRequest = \App\Models\App\LoanRequest::first();
        //return (new \App\Notifications\LoanRequestRejected($loanRequest))->toMail($loanRequest->applicant);
        //dd($loanRequest->applicant()->first());
        Notification::send($loanRequest->applicant()->first(), new \App\Notifications\App\LoanRequestRejected($loanRequest));
    });

});
Route::get('misc/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Silber\Bouncer\Database\HasRolesAndAbilities;

class User extends Authenticatable
{
    use Notifiable, HasRolesAndAbilities;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BackOffice/UserController.php
<?php

namespace App\Http\Controllers\BackOffice;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{

    public function index()
    {
        $users = User::paginate();
        return view('backoffice.user.index', compact('users'));
    }


    public function show($user)
    {
        $user = User::find($user);
        $roles = app('Bouncer')->role()->all();
        return view('backoffice.user.show', compact('user', 'roles'));
    }


    public function edit($user, Request $request)
    {
        $data = $request->except('_token');
        User::updateOrCreate(
            ['id' => $user],
            $data
        );
    }
}

app/Http/Controllers/Front/AppController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\App\LoanRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AppController extends Controller
{

    public function home()
    {
        return view('front.user.home');
    }


    public function loanRequests()
    {
        $data = user('ap')->loanRequests()->latest()->paginate();
        return view('front.user.loan-requests', compact('data'));
    }


    public function loanRequest($loanRequestId, Request $request)
    {
        return view('front.user.loan-request');
    }


    public function showLoanRequest($requestId, Request $request)
    {
        $data = user('ap')->loanRequests()->with('applicant')->find($requestId);
        return view('front.user.loan-request', compact('data'));
    }
}

resources/views/front/user/home.blade.php
@extends('layouts.front.master')

@section('content')

    <div class="row">
        @include('front.user.partials.sidebar')
        <div class="col-lg-9">
            <div class="row">
                <div class="col-sm-6 col-lg-4">
                    <div class="card p-3">
                        <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-blue mr-3">
                      <i class="fe fe-dollar-sign"></i>
                    </span>
                            <div>
                                <h4 class="m-0"><a href="javascript:void(0)">0
                                        <small>Approved Requests</small>
                                    </a></h4>
                                <small class="text-muted">1 waiting request</small>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-lg-4">
                    <div class="card p-3">
                        <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-yellow mr-3">
                      <i class="fe fe-message-square"></i>
                    </span>
                            <div>
                                <h4 class="m-0"><a href="javascript:void(0)">0 <small>Loan Applications</small></a></h4>
                                <small class="text-muted">1 waiting</small>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-lg-4">
                    <div class="card p-3">
                        <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-green mr-3">
                      <i class="fe fe-shopping-cart"></i>
                    </span>
                            <div>
                                <h4 class="m-0"><a href="javascript:void(0)">0 <small>Disbursed Loan</small></a></h4>
                                {{--<small class="text-muted">32 shipped</small>--}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <div class="text-wrap p-lg-6">

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/front/user/loan-request.blade.php
@extends('layouts.front.master')

@section('page-header', 'Loan Requests')

@section('content')

    <div class="page-header">
        <h1 class="page-title">Loan Request</h1>
    </div>
    <div class="row">
        @include('front.user.partials.sidebar')
        <div class="col-lg-9">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12">

                                    <ul style="list-style: none;" class="list-request-loan row">
                                        <li class="col-4">
                                            <span class="_label">Request Status: </span>
                                            <loan-request-status :status="{{$data->request_status}}"></loan-request-status>
                                        </li>
                                        <li class="col-4">
                                            <span class="_label">Offer Status: </span>
                                            <loan-request-offer-status :status="{{$data->offer_status}}"></loan-request-offer-status>
                                        </li>
                                        <li class="col-4">
                                            <span class="_label ">Request Date:</span>
                                            <span class="_label-data">{{ $data->created_at->format('d M Y') }}</span>
                                        </li>
                                        <li class="col-4">
                                            <span class="_label">Amount</span>
                                            <span>{{ toNaira($data->amount) }}</span>
                                        </li>
                                        <li class="col-4">
                                            <span class="_label">Tenor</span>
                                            <span>{{ $data->tenor }} Months</span>
                                        </li>
                                        <li class="col-4">
                                            <span class="_label">Interest Rate</span>
                                            <span>{{ $data->interest_rate_percent }} %</span>
                                        </li>
                                        <li class="col-4">
                                            <span class="_label">Amount Payable Monthly</span>
                                            <span>{{ toNaira($data->monthly_amount_payable) }}</span>
                                        </li>
                                        <li class="col-4">
                                            <span class="_label">Total Amount Payable</span>
                                            <span>{{ toNaira($data->total_amount_payable) }}</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/front/user/loan-requests.blade.php
@extends('layouts.front.master')

@section('content')

    <div class="page-header">
        <h1 class="page-title">Loan Requests</h1>
    </div>
    <div class="row">
        @include('front.user.partials.sidebar')
        <div class="col-lg-9">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if ($data->count())
                            <div class="table-responsive" style="min-height:400px;">
                                <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                                    <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Tenor</th>
                                        <th>Monthly Repayment</th>
                                        <th>Total Repayment</th>
                                        <th>Request Status</th>
                                        <th>Offer Status</th>
                                        <th class="text-center"><i class="icon-settings"></i></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @php $counter = 0; @endphp
                                    @foreach($data as $row)
                                        <tr>
                                            <td>{{ ++$counter }}</td>
                                            <td>{{ $row->created_at->format("d M Y") }}</td>
                                            <td>{{ toNaira($row->amount) }}</td>
                                            <td>{{ $row->tenor }} {{ $row->tenor > 1 ? ' Months' : ' Month' }}</td>
                                            <td>{{ toNaira($emi = emi(7/100, $row->tenor, $row->amount)) }}</td>
                                            <td>{{ toNaira($emi * $row->tenor) }}</td>
                                            <td>
                                                <loan-request-status :status="{{$row->request_status}}"></loan-request-status>
                                            </td>
                                            <td>
                                                <loan-request-offer-status :status="{{$row->offer_status}}"></loan-request-offer-status>
                                            </td>
                                            <td class="text-center">
                                                <div class="item-action dropdown">
                                                    <a href="javascript:void(0)" data-toggle="dropdown" class="icon"><i class="fe fe-more-vertical"></i></a>
                                                    <div class="dropdown-menu dropdown-menu-right">
                                                        <a href="{{route('user.request',['requestId'=>$row->id])}}" class="dropdown-item"><i class="dropdown-icon fe fe-tag"></i> View </a>
                                                        <div class="dropdown-divider"></div>
                                                        <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-link"></i> Withdraw request</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            <div class="card-body">
                                <div class="alert alert-info">
                                    No existing loan request
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection