routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Str;

Route::prefix('back-office')->namespace('BackOffice')->group(function () {
    Auth::routes();

    Route::get('', function () {
        return view('layouts.backoffice.master');
    })->middleware('auth')->name('bo.home');

    Route::prefix('standing-orders')->namespace('SO')->middleware('auth')->name('so.')->group(function () {
        Route::get('pending', 'SoController@pending')->name('pending');
        Route::get('pending/{payment_ref}/view', 'SoController@view')->name('pending.view');
        Route::get('activated', 'SoController@activated')->name('activated');
        Route::get('invalid', 'SoController@invalid')->name('invalid');
    });

    Route::prefix('roles')->namespace('Roles')->middleware('auth')->group(function () {
        Route::get('/', 'RoleController@index')->name('roles.index');
        Route::post('/', 'RoleController@store')->name('roles.store');
        Route::delete('/{role}', 'RoleController@destroy')->name('roles.destroy');

        Route::get('assign', 'AssignRolesToPermsController@index')->name('roles.assign');
        Route::post('assign', 'AssignRolesToPermsController@store')->name('assign.create');
    });
    Route::prefix('abilities')->namespace('Roles')->middleware('auth')->group(function () {
        Route::get('/', 'AbilityController@index')->name('abilities.index');
        Route::post('/', 'AbilityController@store')->name('abilities.store');
        Route::delete('/{ability}', 'AbilityController@destroy')->name('abilities.destroy');
    });
    Route::prefix('users')->middleware('auth')->group(function () {
        Route::get('/', 'UserController@index')->name('users.index');
        Route::get('show/{user}', 'UserController@show')->name('users.show');
    });

    Route::prefix('loan-app')->middleware('auth')->namespace('LoanApp')->name('bo.loan.')->group(function () {
        Route::get('loan-requests', 'LoanRequestController@index')->name('requests');
        Route::get('{id}/loan-request', 'LoanRequestController@show')->name('show');

        Route::get('remita-salary-history', 'LoanRequestController@remitaSalaryHistory');
    });


    Route::get('test', function (\App\Library\SalaryHistoryWrapper $wrapper, \App\Library\DoScoring $doScoring) {

        dd(
            \App\Models\Transaction::first()->standingOrder->first(),
            \App\Models\Transaction::first()->Customer->first(),
            \App\Models\Transaction::first()->authorization()->first()
        );


        //echo toNaira(roundNearestHundredUp(pv(7/100, 6, 21000)));
    });


});
Route::get('start-loan-request', function () {
    return view('front.loan-request.start');
})->name('start.request');
Route::prefix('auth')->namespace('Front\Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('auth.login');
    Route::post('login', 'LoginController@login')->name('auth.post.login');
    Route::post('logout', 'LoginController@logout');
    Route::get('logout', 'LoginController@logout')->name('auth.logout');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail');
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm');
    Route::post('register', 'RegisterController@register');
    Route::get('register', 'RegisterController@showRegistrationForm');

    Route::get('home', function () {
        return 'Auth Home';
    })->middleware('ap.auth:ap')->name('auth.home');
});

Route::prefix('user')->namespace('Front')->middleware('ap.auth:ap')->name('user.')->group(function () {
    Route::get('home', 'AppController@home')->name('home');
    Route::get('loan-requests', 'AppController@loanRequests')->name('requests');
    Route::get('/loan-request/{requestId}/view', 'AppController@showLoanRequest')->name('request');
});


Route::get('/', function () {
    return view('welcome');
});

Route::prefix('standing-order')->namespace('StandingOrder')->group(function () {

    Route::get('', 'StandingOrderController@create')->name('so.create');
    Route::get('/', 'StandingOrderController@create')->name('so.create');
    Route::get('create', 'StandingOrderController@create')->name('so.create');
    Route::get('verify-initial-charge', 'StandingOrderController@verify')->name('so.verify.reference');

    Route::get('test', 'StandingOrderController@test');
});

Route::get('backoffice/standing-order', function () {

    $p = new ShegunBabs\PayStack\PayStack(env('PAYSTACK_SECRET_KEY'));
    $response = $p->transaction->initialize(['email' => 'shegun.babs@gmail.com', 'amount' => 1000 * 100, 'callback_url' => 'http://loanapp.local/standing-order/verify-initial-charge']);
    $url = $response['response']->data->authorization_url;
    dd($url);

    //ShegunBabs\PayStack\call_url($url);

    //return view('bo.standing-order');
});

Route::get('standing-order/verify-initial-charges', function (Request $request) {

    $trxref = $request->query('trxref');
    $ref = $request->query('reference');

    if (empty($ref)) {
        return view('bo.so.noref');
    }


    $p = new \ShegunBabs\PayStack\PayStack(env('PAYSTACK_SECRET_KEY'));
    $res = $p->transaction->verify($ref);
    Log::info($res['response']);
    dd($res['response']);
});

Route::get('privacy-policy', 'FrontOffice\WebController@privacy');

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('test')->group(function () {

    Route::get('sms', function(){
        $res = app('Infobip')->sms->single([

        ]);
    });

    Route::get('mail', function () {
        $loanRequest = \App\Models\App\LoanRequest::first();
        //return (new \App\Notifications\LoanRequestRejected($loanRequest))->toMail($loanRequest->applicant);
        //dd($loanRequest->applicant()->first());
        Notification::send($loanRequest->applicant()->first(), new \App\Notifications\App\LoanRequestRejected($loanRequest));
    });

});
Route::get('misc/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Http/Controllers/BackOffice/LoanApp/LoanRequestController.php
<?php

namespace App\Http\Controllers\BackOffice\LoanApp;

use App\Events\LoanRequestRejected;
use App\Jobs\Remita\GetSalaryHistory;
use App\Models\App\LoanRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LoanRequestController extends Controller
{

    public function index(Request $request)
    {
        $statusNumber = null;
        $status = $request->query('status');
        if ($status)
            $statusNumber = $this->getLoanRequestStatus($status);

        $data = $status ? LoanRequest::where('request_status', $statusNumber)->paginate(20) : LoanRequest::paginate(20);
        return view('backoffice.loan-app.loan-requests', compact('data'));
    }


    public function show($id, Request $request)
    {
        $data = LoanRequest::with('applicant')->find($id);

        if ( count($request->query) )
            return $this->ifRequestQueryExistsRunIt($data);

        $lrs = loanRepaymentSchedule($data->interest_rate_percent, $data->tenor, $data->amount, today());
        return view('backoffice.loan-app.loan-request', compact('data', 'lrs'));
    }


    public function remitaSalaryHistory()
    {
        return view('backoffice.loan-app.remita-data');
    }


    private function getLoanRequestStatus($status)
    {
        $loanRequestStatuses = [
            'pending' => 0,
            'on-hold' => 1,
            'processing' => 2,
            'rejected' => 3,
            'processed' => 4,
            'withdrawn' => 5,
        ];
        return $loanRequestStatuses[$status];
    }

    private function ifRequestQueryExistsRunIt($loanRequestModel)
    {
        $this->rejectRequest($loanRequestModel);
        $this->checkRemitaData($loanRequestModel);
        return redirect()->back();
    }

    private function rejectRequest($loanRequestModel)
    {
        $request = app('request');
        if ($request->query('rejectRequest') && ($loanRequestModel->statusPending() || $loanRequestModel->statusOnHold() || $loanRequestModel->statusRejected()))
        {
            $loanRequestModel->setStatusRejected();
            event(new LoanRequestRejected($loanRequestModel));
            flash()->overlay('Loan Request rejected successfully');
        }
    }

    private function checkRemitaData($dataModel)
    {
        $request = app('request');
        if ($request->query('checkRemitaData') && !$dataModel->applicant->hasRemitaData()) {
            GetSalaryHistory::dispatch($dataModel->applicant->mobile, $dataModel->applicant->id);
            flash()->overlay('Remita Data request sent. Please refresh after a few seconds');
        }
    }
}

app/Http/Controllers/BackOffice/Roles/AbilityController.php
<?php

namespace App\Http\Controllers\BackOffice\Roles;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AbilityController extends Controller
{

    public function index()
    {
        $data = app('Bouncer')->ability()->select('name', 'title')->get();
        return view('backoffice.abilities.index', compact('data'));
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'title' => 'required|string',
        ]);

        $bouncer = app('Bouncer');
        $bouncer->ability()->updateOrCreate(
            ['name' => strtolower($request->name)],
            ['title' => ucwords($request->title),]
        );

        flash()->overlay('Ability created successfully');
        return redirect()->back();
    }


    public function destroy($ability)
    {
        app('Bouncer')->ability()->where('name', $ability)->delete();
        flash()->overlay('Ability deleted');
        return redirect()->back();
    }
}

app/Http/Controllers/BackOffice/Roles/AssignRolesToPermsController.php
<?php

namespace App\Http\Controllers\BackOffice\Roles;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AssignRolesToPermsController extends Controller
{


    public function index()
    {
        $roles = app('Bouncer')->role()->all();
        $abilities = app('Bouncer')->ability()->select('name', 'title')->get();

//        dd(
//            app('Bouncer')->role()->where('name', 'super_admin')->first()->getAbilities()->pluck('name')->toArray()
//        );

        return view('backoffice.roles.assign-perms', compact('roles', 'abilities'));
    }


    public function store(Request $request)
    {
        //dd($request->all());
        $role = $request->role;
        $abilities = $request->ability;

        //remove all abilities from role
        app('Bouncer')->sync($role)->abilities([]);

        if ( !is_null($abilities) ) {
            //assign abilities to role
            foreach ($abilities as $ability) {
                app('Bouncer')->allow($role)->to($ability);
            }
        }

        flash()->overlay('Abilities set.');
        return redirect()->back();
    }
}

app/Http/Controllers/BackOffice/Roles/RoleController.php
<?php

namespace App\Http\Controllers\BackOffice\Roles;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Silber\Bouncer\Bouncer;

class RoleController extends Controller
{


    public function index()
    {
        $data = app('Bouncer')->role()->select('name', 'title')->get();
        return view('backoffice.roles.index', compact('data'));
    }


    public function create()
    {
        return view('backoffice.roles.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'title' => 'required|string',
        ]);

        $bouncer = Bouncer::create();
        $bouncer->role()->updateOrCreate(
            ['name' => strtolower($request->name)],
            ['title' => ucwords($request->title),]
        );

        flash()->overlay('Role created successfully');
        return redirect()->back();
    }


    public function destroy($role)
    {
        app('Bouncer')->role()->where('name', $role)->delete();
        flash()->overlay('Role deleted');
        return redirect()->back();
    }
}

app/Http/Controllers/BackOffice/SO/SoController.php
<?php

namespace App\Http\Controllers\BackOffice\SO;

use App\Models\SO\StandingOrder;
use App\Models\Transaction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SoController extends Controller
{

    public function activated()
    {
        $data = StandingOrder::where('activated', 1)->latest()->paginate();
        return view('backoffice.so.activated', compact('data'));
    }


    public function pending()
    {
        $data = StandingOrder::where('activated', 0)->latest()->paginate();
        return view('backoffice.so.pending', compact('data'));
    }


    public function invalid()
    {
        $data = StandingOrder::where('authorization_reusable', 0)->latest()->paginate();
        return view('backoffice.so.invalid', compact('data'));
    }


    public function view($payment_ref)
    {
        $data = StandingOrder::with('standingOrderRepayment')->where('payment_reference', $payment_ref)->first();
        $trans = Transaction::with('authorization')->where('reference', $data->payment_reference)->first();
        return view('backoffice.so.view', compact('data', 'trans'));
    }
}

app/Http/Controllers/BackOffice/UserController.php
<?php

namespace App\Http\Controllers\BackOffice;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{

    public function index()
    {
        $users = User::paginate();
        return view('backoffice.user.index', compact('users'));
    }


    public function show($user)
    {
        $user = User::find($user);
        $roles = app('Bouncer')->role()->all();
        return view('backoffice.user.show', compact('user', 'roles'));
    }


    public function edit($user, Request $request)
    {
        $data = $request->except('_token');
        User::updateOrCreate(
            ['id' => $user],
            $data
        );
    }
}

resources/views/backoffice/loan-app/loan-request.blade.php
@extends('layouts.backoffice.master')

@section('page-header', 'Loan Request')

@section('content')

    <div class="row">
        <div class="col-xl-3 col-lg-3 col-md-5 col-sm-12 col-12">
            <div class="card">
                <div class="card-body">
                    <div class="user-avatar text-center d-block">
                        <img src="assets/images/avatar-1.jpg" alt="User Avatar" class="rounded-circle user-avatar-xxl">
                    </div>
                    <div class="text-center">
                        <h2 class="font-24 mb-0">{{ ucwords($data->applicant->firstname. ' ' .$data->applicant->lastname) }}</h2>
                        {{--<p>Project Manager @Influnce</p>--}}
                    </div>
                </div>
                <div class="card-body border-top">
                    <h3 class="font-16">Contact Information</h3>
                    <div class="">
                        <ul class="list-unstyled mb-0">
                            <li class="mb-2"><i class="fas fa-fw fa-envelope mr-2"></i>{{ $data->applicant->email }}</li>
                            <li class="mb-0"><i class="fas fa-fw fa-phone mr-2"></i>{{ $data->applicant->mobile }}</li>
                        </ul>
                    </div>
                </div>
                <div class="card-body border-top">
                    <h3 class="font-16">Status</h3>
                    <h1 class="mb-0">{{ $data->statusText() }}</h1><h5>{{$data->offerStatus()}}</h5>
                </div>
                <div class="card-body border-top">
                    @if ($data->applicant->isNotRemitaCustomer() && !$data->statusRejected())
                        <a class="btn btn-warning m-2" onclick="javascript: return confirm('Are you sure')"
                           href="{{route('bo.loan.show', ['id' => $data->id, 'rejectRequest'=>str_random()])}}">Reject Request</a>
                    @else

                        @if($data->statusPending())
                            <button class="btn-primary display-block m-2">Put Request On-Hold</button>
                            <button class="btn-primary display-block m-2">Set Request Processing</button>
                            <button class="btn-warning display-block m-2">Reject Request</button>
                        @endif

                        @if ( $data->statusOnHold() )
                            <button class="btn-primary display-block m-2">Set Request Processing</button>
                            <button class="btn-warning display-block m-2">Reject Request</button>
                        @endif

                        @if( $data->statusProcessing() )
                            <button class="btn-warning display-block m-2">Reject Request</button>
                            <button class="btn-success display-block m-2">Give Offer</button>
                        @endif

                        @if( $data->statusRejected() )
                            <span>Request Truncated.</span>
                        @endif


                    @endif

                </div>

            </div>
        </div>

        <div class="col-xl-9 col-lg-9 col-md-7 col-sm-12 col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <h3>Request Details</h3>
                            <ul style="list-style: none;" class="list-request-loan">
                                <li>
                                    <span class="_label">Request Date</span>
                                    <span class="_label-data">{{ $data->created_at->format('d M Y') }}</span>
                                </li>
                                <li>
                                    <span class="_label">Amount</span>
                                    <span>{{ toNaira($data->amount) }}</span>
                                </li>
                                <li>
                                    <span class="_label">Tenor</span>
                                    <span>{{ $data->tenor }}</span>
                                </li>
                                <li>
                                    <span class="_label">Interest Rate</span>
                                    <span>{{ $data->interest_rate_percent }} %</span>
                                </li>
                                <li>
                                    <span class="_label">Amount Payable Monthly</span>
                                    <span>{{ toNaira($data->monthly_amount_payable) }}</span>
                                </li>
                                <li>
                                    <span class="_label">Total Amount Payable</span>
                                    <span>{{ toNaira($data->total_amount_payable) }}</span>
                                </li>
                            </ul>
                        </div>
                        <div class="col-12 col-md-6 border-left">
                            <h3>Remita Salary Details</h3>
                            @if ($data->applicant->hasRemitaData())
                                <ul class="list-request-loan">
                                    <li>
                                        <span class="_label">Customer ID</span>
                                        <span class="_label-data">{{ $data->applicant->remitaData->customer_id }}</span>
                                    </li>
                                    <li>
                                        <span class="_label">Account Number</span>
                                        <span class="_label-data">{{ $data->applicant->remitaData->account_number }}</span>
                                    </li>
                                    <li>
                                        <span class="_label">Bank Name</span>
                                    </li>
                                    <li>
                                        <span class="_label">Company Name</span>
                                        <span class="_label-data">{{ $data->applicant->remitaData->company_name }}</span>
                                    </li>
                                    <li>
                                        <span class="_label">First Payment Date</span>
                                        <span class="_label-data">{{ $data->applicant->remitaData->first_payment_date->format("d M Y") }}</span>
                                    </li>
                                    <li>
                                        <span class="_label">Salary Amount / Average Salary</span>
                                        <span class="_label-data">{{ toNaira($data->applicant->remitaData->remitaSalaryPayments->first()->amount). " / "
                                        .toNaira($data->applicant->remitaData->remitaSalaryPayments->avg('amount')) }}</span>
                                    </li>
                                </ul>
                            @else

                                <div class="alert alert-info alert-important">
                                    This customer has no remita data.
                                </div>

                                @if( $data->applicant->hasRemitaSalaryResponseData() )
                                    <div class="alert alert-warning alert-important">
                                        This customer does not exist on Remita <br>
                                        [<a href="{{route('bo.loan.show', ['id' => $data->id, 'checkRemitaData'=>str_random()])}}" class="">Force Check for Remita Data</a>]
                                    </div>
                                @else
                                    <a href="{{route('bo.loan.show', ['id' => $data->id, 'checkRemitaData'=>str_random()])}}" class="btn btn-sm btn-primary">Check for Remita Data</a>
                                @endif

                            @endif

                        </div>
                    </div>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="bg-light">
                            <tr class="border-0">
                                <th class="border-0">#</th>
                                <th class="border-0">Date</th>
                                <th class="border-0">Principal Amount</th>
                                <th class="border-0">Interest Amount</th>
                                <th class="border-0">Total Amount Payable</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php $counter = 0 @endphp
                            @foreach($lrs['data'] as $item)
                                <tr>
                                    <td>{{ ++$counter }}</td>
                                    <td> {{ $item['due_date'] }} </td>
                                    <td> {{ toNaira($item['principal']) }} </td>
                                    <td>{{ toNaira($item['interest']) }}</td>
                                    <td>{{ toNaira($item['total']) }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- ============================================================== -->
    <!-- end campaign tab one -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- end campaign data -->
    <!-- ============================================================== -->
    </div>

@endsection

resources/views/backoffice/loan-app/loan-requests.blade.php
@extends('layouts.backoffice.master')

@section('page-header', 'Loan Requests')

@section('content')

    <div class="card">
        <h5 class="card-header">Loan Requests</h5>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table">
                    <thead class="bg-light">
                    <tr class="border-0">
                        <th class="border-0">#</th>
                        <th class="border-0">Date</th>
                        <th class="border-0">Customer Name</th>
                        <th class="border-0">Loan Amount</th>
                        <th class="border-0">Loan Tenor/Interest Rate</th>
                        <th class="border-0">Monthly Repayment</th>
                        <th class="border-0">Total Repayment</th>
                        <th class="border-0">Request Status</th>
                        <th class="border-0">Offer Status</th>
                        <th class="text-center"><i class="icon-settings"></i></th>
                    </tr>
                    </thead>
                    <tbody>
                    @php $counter=0; @endphp
                    @foreach($data as $row)
                        <tr>
                            <td>{{ ++$counter }}</td>
                            <td>{{ $row->created_at->format('d M Y') }}</td>
                            <td>{{ ucwords($row->applicant->firstname. ' ' .$row->applicant->lastname) }}</td>
                            <td>{{ toNaira($row->amount) }}</td>
                            <td>{{ $row->tenor. ' Months' . ' / ' .$row->interest_rate_percent. '%' }}</td>
                            <td>{{ toNaira($row->monthly_amount_payable) }}</td>
                            <td>{{ toNaira($row->total_amount_payable) }}</td>
                            <td>
                                <loan-request-status :status="{{$row->request_status}}"></loan-request-status>
                            </td>
                            <td>
                                <loan-request-offer-status :status="{{$row->offer_status}}"></loan-request-offer-status>
                            </td>
                            <td>
                            <td class="text-center">
                                <div class="item-action dropdown">
                                    <a href="javascript:void(0)" data-toggle="dropdown" class="icon">
                                        <i class="fe fe-more-vertical"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a href="{{route('bo.loan.show',['id'=>$row->id])}}" class="dropdown-item"> <i class="dropdown-icon fe fe-tag"></i> View </a>
                                        <div class="dropdown-divider"></div>
                                        <a href="javascript:void(0)" class="dropdown-item">
                                            <i class="dropdown-icon fe fe-link"></i> Withdraw request</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach

                    <tr>
                        <td colspan="10">
                            <select name="request_status" id="request_status" class="form-control float-right" style="width:200px;">
                                <option value="">Choose Request Status</option>
                                <option value="">All</option>
                                <option value="pending">Pending</option>
                                <option value="on-hold">On-Hold</option>
                                <option value="processing">Processing</option>
                                <option value="rejected">Rejected</option>
                                <option value="processed">Processed</option>
                                <option value="withdrawn">Withdrawn</option>
                            </select>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script>
        let $select = document.getElementById('request_status');
        var $url = "{{ route('bo.loan.requests') }}";
        $select.addEventListener('change', function(){
            let $option = this.options[this.selectedIndex].value
            if ($option) {
                $link = $url + '?status=' + $option;
            }else {
                $link = $url;
            }
           window.location.href = $link
        });
    </script>
@endpush

resources/views/backoffice/loan-app/remita-data.blade.php
@extends('layouts.backoffice.master')

@section('page-header', 'Pull Remita Data')

@section('content')

    <div class="row">
        <div class="col-12">
            <remita-salary-history></remita-salary-history>
        </div>
    </div>

@endsection